travis:
  secure:
    BINSTAR_TOKEN: TANvfiIFa613nL295E7fkRrLKu3Al5FR2qTNfLqe4oJHbihhcGF3YC8PFF2Wn00Fmk5xdLlSk1N9ERAq0VLSbUwmqAG6EM380Dfi6Cvin6dqeTBnuQHkXhoU7pBBXyQXK0WS9HPtf/FWB5eEmU/YUC3SVlTjniT+6zqY3Cpg1KaqSAgKDodAFRWCzJ3j5KwdaI/A8AjNG8rdfevV3iWPYqA2B46+5S3lMYAY3tmM8VWgT6pLNlF6qpfFyTBLz+TgYflsiGCJ509TVkqnXwg4UOXCnoD6gxUDvsyjGnzz33uGWk36K9CqaATPhsySQhBqZdOelDNYQB1iwOe86kvt2Yn54MB4ydBSLC+ql5Hn1hgykLOwJ0JrMNezWpKut4C5mKv7aEiAy1K/rD35Sppviw+lvWb7YIsxB5nPeutLQymGbH2UbNxCNY/PDfeZUoLCBLFhSsgqwpcSFg+xDanDikk2yMnAQ6Tli6snjAkUjBLxhjYDAjAwL52IJJNHkQ+vuA3sklR5QOFf7Ngb2QzTufOCNIhfIx5+9SFHPk95HUU49amVlTvXquyvmgWcJL+zcR3KpNcW2s67e39lDpNkhRxl0bLHIWVxijQnUip7tgSywiUg1qIku5EE6NfwWCvQWOX3cc85s2EqonkL3CjOzR12QIRWdv+GQ9duBkrZ4xs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
